version: '2'
services:
    stockline-app:
        image: stockline
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://stockline-mysql:3306/stockline?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=stockline-elasticsearch:9300
        ports:
            - 8080:8080
    stockline-mysql:
        extends:
            file: mysql.yml
            service: stockline-mysql
    stockline-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: stockline-elasticsearch
